### ISSUE TITLE
Style for links not applies on site

### ISSUE THREAD

**Issue by robertdijk** [verwoerd/chipcie-poc#9]
On for example the archive page, the color for links is wrong.

<img width="646" alt="Schermafbeelding 2022-08-25 om 20 33 28" src="https://user-images.githubusercontent.com/13507227/186742745-467cf583-5d01-4ba5-9b82-77c61da6ece6.png">
 
While on on the page of the archive itself, it's right:
<img width="818" alt="Schermafbeelding 2022-08-25 om 20 33 37" src="https://user-images.githubusercontent.com/13507227/186742828-f6dce389-4304-4996-a539-0609be074b23.png">

It seems like the same stylesheet is used on both pages (`/ananke/css/main.min.css`), but the style
```css
.nested-links a {
    color: #357edd;
    transition: color .15s ease-in;
}
```
does not get applied to the links on the archive page, while it does work on the other pages.
